package bayern.steinbrecher.dbConnector.query;

import org.jetbrains.annotations.NotNull;

import java.util.Objects;

/**
 * @author Stefan Huber
 * @since 0.7
 */
public class QueryCondition<T> {
    private final String sqlExpression;

    /**
     * FIXME Solely {@link QueryOperator} should be allowed to create instances.
     *
     * @param sqlExpression The SQL ready sqlExpression generated by {@link QueryOperator}
     */
    QueryCondition(@NotNull String sqlExpression) {
        this.sqlExpression = Objects.requireNonNull(sqlExpression);
    }

    @NotNull
    public String getSqlExpression() {
        return sqlExpression;
    }
}
