package bayern.steinbrecher.dbConnector.query;

import org.jetbrains.annotations.NotNull;

import java.util.Objects;

/**
 * @author Stefan Huber
 * @since 0.7
 */
public class QueryCondition<T> {
    private final String condition;

    /**
     * FIXME Solely {@link QueryOperator} should be allowed to create instances.
     *
     * @param condition The SQL ready condition generated by {@link QueryOperator}
     */
    QueryCondition(@NotNull String condition) {
        this.condition = Objects.requireNonNull(condition);
    }

    @NotNull
    public String getCondition() {
        return condition;
    }
}
